
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1811257
 */
public class CreditCard extends PaymentCard {

    private int amountOwed;

    public CreditCard(String securityCode, int limit, Date expiryDate, String cardHolderName, String cardNumber) {
        super(securityCode, limit, expiryDate, cardHolderName, cardNumber);
        this.amountOwed = 0;
        if (limit < 100 || limit > 5000) {
            throw new IllegalArgumentException("Limit must be within 100 and 5000");
        }
    }

    public boolean checkAvailableFunds(int amount) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public boolean withdraw(int amount) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void payCard(int amount) {
        this.amountOwed =- amountOwed;
    }
    //notify(int amount)

    /*
    To keep your credit score in a good standing, the user should not exceed 50% of the card limit.
    The warning generated by the wallet should not prohibit the user from exceeding the 50% threshold.
     */
}
